### ISSUE TITLE
The package name doesn't fit the Effective GO guideline

### ISSUE THREAD

**Issue by d6o** [astrolink/GoMetricMiddleware#1]
[Here](https://github.com/astrolink/GoMetricMiddleware/blob/master/middleware.go#L1) you define the package name as `GoMetricMiddleware`, but a more appropriate name would be something like `metrics`. There is an excellent post on GO blog about it, you can check it [here](https://blog.golang.org/package-names).

**Comment by isfonzar** [comment]
Package name has been changed.
Thank you.
